/**
 * ARTA Auto-Generated Cypress Test Suite
 * Requirement: REQ-017 — Checkout Payment Processing
 * Risk: P0 Critical | Tool: Cypress 13 (TypeScript)
 * Generated by ARTA Automation Engineer Agent
 *
 * Run: npx cypress run --spec src/automation/cypress/checkout.cy.ts
 */

/// <reference types="cypress" />

// ── Test Data ─────────────────────────────────────────────────────────────────

const VALID_CARD = {
  number: '4111111111111111',
  expiry: '12/28',
  cvv:    '123',
  holder: 'Test User',
};

const EXPIRED_CARD  = { number: '4111111111111111', expiry: '01/20', cvv: '123' };
const DECLINED_CARD = { number: '4000000000000002', expiry: '12/28', cvv: '123' };

const VALID_ADDRESS = {
  line1:    '1 Test Street',
  city:     'London',
  postcode: 'SW1A 1AA',
  country:  'GB',
};

// ── Custom Commands ────────────────────────────────────────────────────────────
// These would normally go in cypress/support/commands.ts
// Included here for self-contained demonstration.

Cypress.Commands.add('addToCart', (sku: string, qty = 1) => {
  cy.request('POST', '/api/cart', { sku, qty }).its('status').should('eq', 200);
});

Cypress.Commands.add('fillPaymentForm', (card: typeof VALID_CARD) => {
  cy.get('[data-testid="card-number"]').clear().type(card.number);
  cy.get('[data-testid="card-expiry"]').clear().type(card.expiry);
  cy.get('[data-testid="card-cvv"]').clear().type(card.cvv);
});

Cypress.Commands.add('fillBillingAddress', (address: typeof VALID_ADDRESS) => {
  cy.get('[data-testid="billing-line1"]').clear().type(address.line1);
  cy.get('[data-testid="billing-city"]').clear().type(address.city);
  cy.get('[data-testid="billing-postcode"]').clear().type(address.postcode);
});

Cypress.Commands.add('placeOrder', () => {
  cy.get('[data-testid="place-order-btn"]').click();
});

// Extend Cypress namespace
declare global {
  namespace Cypress {
    interface Chainable {
      addToCart(sku: string, qty?: number): Chainable<void>;
      fillPaymentForm(card: typeof VALID_CARD): Chainable<void>;
      fillBillingAddress(address: typeof VALID_ADDRESS): Chainable<void>;
      placeOrder(): Chainable<void>;
    }
  }
}

// ── Test Suite ────────────────────────────────────────────────────────────────

describe('REQ-017 · Checkout Payment Processing · P0 Critical', () => {

  beforeEach(() => {
    // Deterministic cart seeding via API (not UI)
    cy.request('POST', '/api/test/seed-cart', {
      items: [{ sku: 'SKU-001', name: 'Test Product', price: 29.99, qty: 2 }],
    });
    // Navigate to checkout
    cy.visit('/checkout');
    cy.get('[data-testid="checkout-form"]').should('be.visible');
  });

  afterEach(() => {
    // Clean up test orders via API
    cy.request('DELETE', '/api/test/orders?session=latest').then((res) => {
      expect(res.status).to.be.oneOf([200, 204, 404]);
    });
  });

  // ── AC-001: Valid payment processes within 3s ────────────────────────────

  it('TC-CY-001: Visa checkout completes within 3 seconds', () => {
    cy.fillPaymentForm(VALID_CARD);
    cy.fillBillingAddress(VALID_ADDRESS);

    const startTime = Date.now();
    cy.placeOrder();

    cy.get('[data-testid="order-confirm"]', { timeout: 3000 })
      .should('be.visible')
      .and('contain.text', 'Order confirmed')
      .then(() => {
        const elapsed = Date.now() - startTime;
        expect(elapsed, `Payment took ${elapsed}ms — SLA: < 3000ms`).to.be.lessThan(3000);
      });

    // Verify order total
    cy.get('[data-testid="order-total"]').should('contain.text', '59.98');
  });

  it('TC-CY-002: Order confirmation page shows order details', () => {
    cy.fillPaymentForm(VALID_CARD);
    cy.fillBillingAddress(VALID_ADDRESS);
    cy.placeOrder();

    cy.get('[data-testid="order-confirm"]').should('be.visible');
    cy.get('[data-testid="order-number"]').should('match', /ORD-\d+/);
    cy.get('[data-testid="estimated-delivery"]').should('be.visible');
  });

  // ── AC-002: Invalid card shows error without charge ──────────────────────

  it('TC-CY-003: Expired card rejected with error — no charge', () => {
    // Intercept payment API to verify no charge
    cy.intercept('POST', '/api/checkout/payment').as('paymentRequest');

    cy.fillPaymentForm(EXPIRED_CARD);
    cy.fillBillingAddress(VALID_ADDRESS);
    cy.placeOrder();

    // Verify payment was attempted
    cy.wait('@paymentRequest').its('response.statusCode').should('be.oneOf', [400, 422]);

    // Error message shown
    cy.get('[data-testid="payment-error"]')
      .should('be.visible')
      .and('contain.text', 'expired');

    // Confirm no order created
    cy.request('GET', '/api/orders?last=1').its('body.orders').should('have.length', 0);
  });

  it('TC-CY-004: Declined card shows error without exposing decline reason', () => {
    cy.fillPaymentForm(DECLINED_CARD);
    cy.fillBillingAddress(VALID_ADDRESS);
    cy.placeOrder();

    cy.get('[data-testid="payment-error"]')
      .should('be.visible')
      .invoke('text')
      .should('not.contain', 'stolen')      // Must not expose fraud reason
      .should('not.contain', 'blacklisted');
  });

  // ── AC-003: Security tests ────────────────────────────────────────────────

  it('TC-CY-005: XSS payload in billing address does not execute', () => {
    let alertTriggered = false;
    cy.on('window:alert', () => { alertTriggered = true; });

    cy.fillPaymentForm(VALID_CARD);
    cy.get('[data-testid="billing-line1"]').type('<script>alert("xss")</script>');
    cy.get('[data-testid="billing-city"]').type(VALID_ADDRESS.city);
    cy.get('[data-testid="billing-postcode"]').type(VALID_ADDRESS.postcode);
    cy.placeOrder();

    cy.wait(1000).then(() => {
      expect(alertTriggered).to.be.false;
    });
  });

  // ── AC-004: Idempotency — no double charge ────────────────────────────────

  it('TC-CY-006: Double-click on Place Order creates only one transaction', () => {
    cy.fillPaymentForm(VALID_CARD);
    cy.fillBillingAddress(VALID_ADDRESS);

    // Intercept to count payment requests
    let paymentCallCount = 0;
    cy.intercept('POST', '/api/checkout/payment', (req) => {
      paymentCallCount++;
      req.continue();
    }).as('paymentCalls');

    // Double-click the submit button
    cy.get('[data-testid="place-order-btn"]')
      .dblclick()
      .then(() => {
        // Button should be disabled after first click
        cy.get('[data-testid="place-order-btn"]').should('be.disabled');
      });

    cy.get('[data-testid="order-confirm"]', { timeout: 5000 }).should('be.visible');

    // Verify only one payment request was made
    cy.request('GET', '/api/test/transactions?session=latest')
      .its('body.transactions')
      .should('have.length', 1);
  });

  // ── Edge Cases ────────────────────────────────────────────────────────────

  it('TC-CY-007: Empty cart redirects to cart page', () => {
    cy.request('DELETE', '/api/cart/all');
    cy.visit('/checkout');
    cy.url().should('include', '/cart');
    cy.get('[data-testid="empty-cart-message"]').should('be.visible');
  });

  it('TC-CY-008: Network timeout shows retry option to user', () => {
    // Simulate network timeout
    cy.intercept('POST', '/api/checkout/payment', { forceNetworkError: true }).as('paymentTimeout');

    cy.fillPaymentForm(VALID_CARD);
    cy.fillBillingAddress(VALID_ADDRESS);
    cy.placeOrder();

    cy.wait('@paymentTimeout');
    cy.get('[data-testid="payment-retry-btn"]', { timeout: 5000 }).should('be.visible');
    cy.get('[data-testid="payment-error"]').should('contain.text', 'try again');
  });

  // ── AC-003 (security): Additional injection tests ─────────────────────────

  it('TC-CY-009: XSS payload in card number field is sanitized', () => {
    // AC-003: All user input must be sanitized before storage/display
    let alertTriggered = false;
    cy.on('window:alert', () => { alertTriggered = true; });

    cy.intercept('POST', '/api/checkout/payment').as('paymentAttempt');

    cy.get('[data-testid="card-number"]').type('<img src=x onerror=alert(1)>');
    cy.get('[data-testid="card-expiry"]').type('12/28');
    cy.get('[data-testid="card-cvv"]').type('123');
    cy.fillBillingAddress(VALID_ADDRESS);
    cy.placeOrder();

    // Payment should be rejected (invalid card number)
    cy.wait('@paymentAttempt').its('response.statusCode').should('be.oneOf', [400, 422]);

    // No XSS execution
    cy.wait(500).then(() => {
      expect(alertTriggered, 'XSS alert must not fire').to.be.false;
    });

    // Error message shown to user is generic, not reflected payload
    cy.get('[data-testid="payment-error"]')
      .invoke('text')
      .should('not.contain', 'onerror')
      .should('not.contain', '<img');
  });

  // ── AC-005: Authentication boundary ──────────────────────────────────────

  it('TC-CY-010: Unauthenticated user visiting /checkout is redirected to /login', () => {
    // AC-005: Checkout must require an authenticated session
    // Clear session cookie to simulate unauthenticated state
    cy.clearCookies();
    cy.clearLocalStorage();

    cy.visit('/checkout', { failOnStatusCode: false });

    // Should redirect to login
    cy.url().should('include', '/login');

    // Login page should be rendered
    cy.get('[data-testid="login-form"]', { timeout: 5000 }).should('be.visible');

    // After login, user should be returned to checkout
    cy.get('[data-testid="username"]').type('test@example.com');
    cy.get('[data-testid="password"]').type('TestPass123!');
    cy.get('[data-testid="login-submit"]').click();

    cy.url().should('include', '/checkout');
  });
});
