"""
ARTA Auto-Generated Selenium Test Suite
Requirement: REQ-021 — User Authentication (Login)
Risk: P0 Critical | Tool: Selenium 4 + Python pytest
Generated by ARTA Automation Engineer Agent

Run: pytest src/automation/selenium/login.py -v
"""
import time

import pytest
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from webdriver_manager.chrome import ChromeDriverManager


# ── Test Data ─────────────────────────────────────────────────────────────────

VALID_USER    = {"email": "testuser@test.example.com", "password": "Password123!"}
WRONG_PASS    = {"email": "testuser@test.example.com", "password": "wrongpassword"}
UNKNOWN_USER  = {"email": "nobody@test.example.com",   "password": "Password123!"}
INJECTION_USR = {"email": "' OR '1'='1", "password": "'; DROP TABLE users; --"}
XSS_USER      = {"email": "<script>alert('xss')</script>@test.com", "password": "test"}

MAX_LOGIN_ATTEMPTS = 5   # Account lockout threshold from requirement


# ── Page Object ───────────────────────────────────────────────────────────────

class LoginPage:
    """Page Object for the login form."""

    def __init__(self, driver: webdriver.Chrome, base_url: str):
        self.driver = driver
        self.base_url = base_url
        self.wait = WebDriverWait(driver, 10)

    # Locators
    @property
    def email_field(self):
        return self.wait.until(EC.visibility_of_element_located(
            (By.CSS_SELECTOR, "[data-testid='email-input']")
        ))

    @property
    def password_field(self):
        return self.wait.until(EC.visibility_of_element_located(
            (By.CSS_SELECTOR, "[data-testid='password-input']")
        ))

    @property
    def submit_button(self):
        return self.wait.until(EC.element_to_be_clickable(
            (By.CSS_SELECTOR, "[data-testid='login-submit']")
        ))

    @property
    def error_banner(self):
        return self.wait.until(EC.visibility_of_element_located(
            (By.CSS_SELECTOR, "[data-testid='login-error']")
        ))

    @property
    def lockout_banner(self):
        return self.wait.until(EC.visibility_of_element_located(
            (By.CSS_SELECTOR, "[data-testid='account-locked']")
        ))

    @property
    def dashboard_heading(self):
        return self.wait.until(EC.visibility_of_element_located(
            (By.CSS_SELECTOR, "[data-testid='dashboard-title']")
        ))

    # Actions
    def navigate(self):
        self.driver.get(f"{self.base_url}/login")
        self.wait.until(EC.title_contains("Login"))

    def fill_credentials(self, email: str, password: str):
        self.email_field.clear()
        self.email_field.send_keys(email)
        self.password_field.clear()
        self.password_field.send_keys(password)

    def submit(self):
        self.submit_button.click()

    def login(self, email: str, password: str):
        self.fill_credentials(email, password)
        self.submit()

    def get_error_text(self) -> str:
        return self.error_banner.text

    def get_url(self) -> str:
        return self.driver.current_url

    def get_page_source(self) -> str:
        return self.driver.page_source


# ── Fixtures ──────────────────────────────────────────────────────────────────

@pytest.fixture(scope="function")
def driver():
    """Create a Chrome WebDriver per test with headless mode."""
    options = Options()
    options.add_argument("--headless")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("--window-size=1280,720")

    service = Service(ChromeDriverManager().install())
    drv = webdriver.Chrome(service=service, options=options)
    drv.implicitly_wait(0)  # Disable implicit waits — use explicit only
    yield drv
    drv.quit()


@pytest.fixture
def base_url(pytestconfig):
    return pytestconfig.getoption("--base-url", default="http://localhost:3000")


@pytest.fixture
def login_page(driver, base_url):
    return LoginPage(driver, base_url)


def pytest_addoption(parser):
    parser.addoption("--base-url", action="store", default="http://localhost:3000")


# ── Test Cases ────────────────────────────────────────────────────────────────

class TestLoginHappyPath:
    """AC-001: Valid credentials authenticate and redirect to dashboard."""

    def test_successful_login_redirects_to_dashboard(self, login_page):
        """TC-201: Valid email + password → dashboard redirect."""
        login_page.navigate()
        login_page.login(VALID_USER["email"], VALID_USER["password"])

        # Assert redirect to dashboard
        assert "/dashboard" in login_page.get_url(), \
            f"Expected redirect to /dashboard, got: {login_page.get_url()}"
        assert login_page.dashboard_heading.is_displayed()

    def test_successful_login_under_2_seconds(self, login_page):
        """TC-202: Login completes within 2s SLA (AC-001 threshold)."""
        login_page.navigate()
        login_page.fill_credentials(VALID_USER["email"], VALID_USER["password"])

        start = time.time()
        login_page.submit()
        # Wait for dashboard
        WebDriverWait(login_page.driver, 2).until(
            EC.url_contains("/dashboard")
        )
        elapsed = time.time() - start
        assert elapsed < 2.0, f"Login took {elapsed:.2f}s — SLA requires < 2s"


class TestLoginNegativeCases:
    """AC-002: Invalid credentials show clear error without exposing sensitive info."""

    def test_wrong_password_shows_generic_error(self, login_page):
        """TC-203: Wrong password → generic error (no 'password incorrect' specifics)."""
        login_page.navigate()
        login_page.login(WRONG_PASS["email"], WRONG_PASS["password"])

        error_text = login_page.get_error_text()
        # Must show error
        assert len(error_text) > 0, "Expected error message, got empty"
        # Must NOT expose which field is wrong (security: enumeration prevention)
        assert "password" not in error_text.lower(), \
            "Error must not specify 'password' is wrong (user enumeration risk)"
        assert "invalid credentials" in error_text.lower() or \
               "incorrect" in error_text.lower() or \
               "email or password" in error_text.lower()

    def test_unknown_user_shows_same_error_as_wrong_password(self, login_page):
        """TC-204: Unknown user and wrong password show identical errors (timing attack prevention)."""
        login_page.navigate()
        login_page.login(WRONG_PASS["email"], WRONG_PASS["password"])
        wrong_pass_error = login_page.get_error_text()

        login_page.navigate()
        login_page.login(UNKNOWN_USER["email"], UNKNOWN_USER["password"])
        unknown_user_error = login_page.get_error_text()

        # Same error message → prevents user enumeration
        assert wrong_pass_error == unknown_user_error, \
            "Identical error required for wrong-password and unknown-user scenarios"

    def test_empty_email_shows_validation_error(self, login_page):
        """TC-205: Empty email field shows validation before submit."""
        login_page.navigate()
        login_page.login("", VALID_USER["password"])
        # HTML5 required attribute or custom validation
        assert "/login" in login_page.get_url(), "Should remain on login page"


class TestAccountLockout:
    """AC-003: Account locked after N failed attempts."""

    def test_account_locked_after_max_attempts(self, login_page):
        """TC-206: Account locked after 5 consecutive failed logins."""
        login_page.navigate()

        # Attempt login MAX_LOGIN_ATTEMPTS times with wrong password
        for attempt in range(MAX_LOGIN_ATTEMPTS):
            login_page.fill_credentials(WRONG_PASS["email"], WRONG_PASS["password"])
            login_page.submit()
            # Return to login page for next attempt
            if attempt < MAX_LOGIN_ATTEMPTS - 1:
                login_page.navigate()

        # After final attempt, account should be locked
        lockout_text = login_page.lockout_banner.text
        assert lockout_text, "Expected account lockout message"
        assert "locked" in lockout_text.lower() or "suspended" in lockout_text.lower()

    def test_correct_password_fails_when_locked(self, login_page, driver):
        """TC-207: Locked account rejects even correct password."""
        # Pre-condition: lock the account via API
        import requests
        requests.post(
            f"http://localhost:3000/api/test/lock-account",
            json={"email": VALID_USER["email"]},
        )

        login_page.navigate()
        login_page.login(VALID_USER["email"], VALID_USER["password"])

        # Even correct credentials must fail
        assert "/dashboard" not in login_page.get_url()
        assert login_page.lockout_banner.is_displayed()


class TestLoginSecurity:
    """AC-004: Login form resistant to injection and XSS attacks."""

    def test_sql_injection_in_email_field_blocked(self, login_page):
        """TC-208: SQL injection in email does not cause 500 or data exposure."""
        login_page.navigate()
        login_page.login(INJECTION_USR["email"], INJECTION_USR["password"])

        # Must not crash or expose database errors
        page_source = login_page.get_page_source()
        assert "SQL" not in page_source, "SQL error must not be exposed in page"
        assert "syntax error" not in page_source.lower()
        assert "ORA-" not in page_source     # Oracle error
        assert "mysql" not in page_source.lower()
        # Must not be authenticated
        assert "/dashboard" not in login_page.get_url()

    def test_xss_in_email_field_neutralized(self, login_page):
        """TC-209: XSS payload in email field does not execute."""
        dialogs_triggered = []
        login_page.driver.execute_script(
            "window.alert = function(msg) { window.xss_triggered = msg; };"
        )

        login_page.navigate()
        login_page.login(XSS_USER["email"], XSS_USER["password"])

        xss_triggered = login_page.driver.execute_script("return window.xss_triggered;")
        assert xss_triggered is None, f"XSS alert executed with message: {xss_triggered}"

    def test_csrf_token_present_on_form(self, login_page):
        """TC-210: Login form includes CSRF token."""
        login_page.navigate()
        csrf_token = login_page.driver.find_element(
            By.CSS_SELECTOR, "input[name='csrf_token'], meta[name='csrf-token']"
        )
        assert csrf_token is not None, "CSRF token must be present on login form"
        token_value = csrf_token.get_attribute("value") or csrf_token.get_attribute("content")
        assert token_value and len(token_value) > 10, "CSRF token must have a valid value"
